# Generated by Django 4.2.1 on 2023-05-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_contact',
            field=models.BooleanField(default=False),
        ),
    ]
