# Generated by Django 4.2.1 on 2023-06-07 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='all_contacts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.ManyToManyField(related_name='my_contacts', to='account.contact'),
        ),
    ]
