# Generated by Django 4.2.1 on 2023-06-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_contact_user_contact_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
