# Generated by Django 4.2.2 on 2023-06-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_contact_customuser_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='media/default/no-avatar.png', null=True, upload_to='media/'),
        ),
    ]
