# Generated by Django 4.2.2 on 2023-06-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
    ]
