# Generated by Django 4.2.2 on 2023-06-25 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default/no-avatar.png', upload_to='user_avatar/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='blocked_list',
            field=models.ManyToManyField(related_name='blocked_users', to='account.blockeduser'),
        ),
    ]
