# Generated by Django 4.2.2 on 2023-06-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
