# Generated by Django 4.2.2 on 2023-06-19 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='afsfas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasfas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asfadds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
