# Generated by Django 4.2.2 on 2023-06-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_contactlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='profile',
        ),
    ]
