# Generated by Django 4.2.2 on 2023-06-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_afsfas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='media/default/no-avatar.png', upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='afsfas',
        ),
    ]
