# Generated by Django 4.2.2 on 2023-06-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_contact_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='profile',
        ),
    ]
