# Generated by Django 4.2.2 on 2023-06-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_customuser_image_delete_afsfas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='media/default/no-avatar.png', upload_to='user_avatar/'),
        ),
    ]
