# Generated by Django 4.2.2 on 2023-06-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_contact_user_alter_contact_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
