# Generated by Django 4.2.2 on 2023-06-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_customuser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image',
            new_name='avatar',
        ),
    ]
