# Generated by Django 4.2.2 on 2023-06-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
