# Generated by Django 4.2.2 on 2023-06-19 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_blockeduser_customuser_blocked_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockeduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
