# Generated by Django 4.2.2 on 2023-06-25 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_contact_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
