# Generated by Django 4.2.2 on 2023-06-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_contact_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contacts',
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='friend',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
