# Generated by Django 4.2.2 on 2023-06-25 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_customuser_contacts_alter_contactlist_friend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
