# Generated by Django 4.2.2 on 2023-06-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_blockeduser_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blocked_list',
        ),
    ]
