# Generated by Django 4.2.1 on 2023-05-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmessenger', '0002_message_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='curentuser',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
