# Generated by Django 4.2.1 on 2023-05-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djmessenger', '0003_message_curentuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='curentuser',
        ),
    ]
