# Generated by Django 4.2.1 on 2023-06-07 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djmessenger', '0010_message_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='userid',
        ),
        migrations.AddField(
            model_name='message',
            name='msg_receiver',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='msg_receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='msg_sender',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='msg_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
