# Generated by Django 4.2.1 on 2023-06-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmessenger', '0011_remove_message_userid_message_msg_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
