# Generated by Django 4.2.1 on 2023-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmessenger', '0012_file_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_message',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
