# Generated by Django 4.2.2 on 2023-06-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmessenger', '0013_alter_file_message_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File_message',
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
