# Generated by Django 4.2.2 on 2023-06-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmessenger', '0014_delete_file_message_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
