# Generated by Django 4.2.2 on 2023-06-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djmessenger', '0019_profiles_delete_afsfas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
