# Generated by Django 4.2.2 on 2023-06-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmessenger', '0020_delete_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
