# Generated by Django 4.2.2 on 2023-07-20 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djmessenger', '0024_remove_userlist_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='receiver_user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
